(in-package #:lbccl.site)

(declaim (ftype function topbar site-footer lesson-grid write-png))

(defparameter *current-language* :en)

(defparameter *language-labels*
  '((:en
     :html-lang "en"
     :language-name "English"
     :language-short "EN"
     :home-title "Home"
     :lesson "Lesson"
     :lessons "Lessons"
     :source "Full Compiler Source"
     :start-course "Start the Course"
     :read-compiler "Read the Compiler"
     :pipeline-caption "Source -> tokens -> AST -> bytecode -> VM"
     :pipeline-alt "Compiler pipeline illustration generated by Common Lisp"
     :run-title "Run It"
     :run-copy "The site generator and the tiny compiler are both Common Lisp. Build the pages or run the tests with SBCL from this directory."
     :test-note "O runner de testes tambem e codigo fonte Common Lisp: test.lisp"
     :credits-title "Credits"
     :credits-copy "Inspired by the original Let's Build a Compiler course by Jack Crenshaw."
     :credits-link "Original website"
     :source-title "Full Compiler Source"
     :source-deck "This listing is generated from src/tiny-compiler.lisp, the same Common Lisp file used by the tests."
     :previous "Previous"
     :next "Next"
     :full-source "Full compiler source"
     :footer "Original course text is not reproduced here. This is a new Common Lisp teaching site inspired by the public compiler-building tradition and generated from Common Lisp source.")
    (:pt-br
     :html-lang "pt-BR"
     :language-name "Portugues"
     :language-short "PT-BR"
     :home-title "Inicio"
     :lesson "Licao"
     :lessons "Licoes"
     :source "Codigo Completo do Compilador"
     :start-course "Comecar o Curso"
     :read-compiler "Ler o Compilador"
     :pipeline-caption "Fonte -> tokens -> AST -> bytecode -> VM"
     :pipeline-alt "Ilustracao do pipeline do compilador gerada por Common Lisp"
     :run-title "Execute"
     :run-copy "O gerador do site e o compilador Tiny sao Common Lisp. Construa as paginas ou rode os testes com SBCL a partir deste diretorio."
     :test-note "O runner de testes tambem e codigo fonte Common Lisp: test.lisp"
     :credits-title "Creditos"
     :credits-copy "Inspirado pelo curso original Let's Build a Compiler, de Jack Crenshaw."
     :credits-link "Site original"
     :source-title "Codigo Completo do Compilador"
     :source-deck "Esta listagem e gerada a partir de src/tiny-compiler.lisp, o mesmo arquivo Common Lisp usado pelos testes."
     :previous "Anterior"
     :next "Proxima"
     :full-source "Codigo completo do compilador"
     :footer "O texto original do curso nao e reproduzido aqui. Este e um novo site de ensino em Common Lisp inspirado pela tradicao publica de construcao de compiladores e gerado a partir de codigo Common Lisp.")))

(defun label (key)
  (getf (cdr (assoc *current-language* *language-labels*)) key))

(defun current-course-title ()
  (course-title-for-language *current-language*))

(defun current-course-deck ()
  (course-deck-for-language *current-language*))

(defun current-lessons ()
  (lessons-for-language *current-language*))

(defun localized-page-url (target-language filename)
  (cond
    ((eq target-language *current-language*) filename)
    ((eq target-language :en) (format nil "../~A" filename))
    (t (format nil "pt-br/~A" filename))))

(defun asset-url (filename)
  (if (eq *current-language* :en)
      (format nil "assets/~A" filename)
      (format nil "../assets/~A" filename)))

(defun ensure-directory (pathname)
  (ensure-directories-exist (merge-pathnames "sentinel" pathname))
  pathname)

(defun path (directory name)
  (merge-pathnames name directory))

(defun escape-html (value)
  (with-output-to-string (stream)
    (loop for character across (princ-to-string value) do
      (case character
        (#\< (write-string "&lt;" stream))
        (#\> (write-string "&gt;" stream))
        (#\& (write-string "&amp;" stream))
        (#\" (write-string "&quot;" stream))
        (#\' (write-string "&#39;" stream))
        (otherwise (write-char character stream))))))

(defun html-attrs (attrs)
  (with-output-to-string (stream)
    (loop for (name value) on attrs by #'cddr
          when value do
            (format stream " ~A=\"~A\"" name (escape-html value)))))

(defun element (name attrs &rest body)
  (with-output-to-string (stream)
    (format stream "<~A~A>" name (html-attrs attrs))
    (dolist (part body)
      (write-string part stream))
    (format stream "</~A>" name)))

(defun void-element (name attrs)
  (format nil "<~A~A>" name (html-attrs attrs)))

(defun link-to (href label &key class)
  (element "a" (list "href" href "class" class) (escape-html label)))

(defun code-block (code)
  (element "pre" '("class" "code")
           (element "code" '() (escape-html code))))

(defun paragraph-html (text)
  (element "p" '() (escape-html text)))

(defun slug-file (lesson)
  (format nil "~A.html" (lesson-slug lesson)))

(defun lesson-url (lesson)
  (slug-file lesson))

(defun css ()
  (format nil "~{~A~%~}"
          '(":root {"
            "  color-scheme: light;"
            "  --paper: #f8fafc;"
            "  --panel: #ffffff;"
            "  --ink: #18181b;"
            "  --muted: #52525b;"
            "  --line: #d4d4d8;"
            "  --teal: #0f766e;"
            "  --red: #b91c1c;"
            "  --amber: #b7791f;"
            "  --code: #111827;"
            "  --code-edge: #374151;"
            "}"
            "* { box-sizing: border-box; }"
            "body {"
            "  margin: 0;"
            "  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;"
            "  background: var(--paper);"
            "  color: var(--ink);"
            "  line-height: 1.55;"
            "}"
            "a { color: var(--teal); text-decoration-thickness: 0.08em; text-underline-offset: 0.18em; }"
            ".topbar {"
            "  position: sticky;"
            "  top: 0;"
            "  z-index: 10;"
            "  display: flex;"
            "  align-items: center;"
            "  justify-content: space-between;"
            "  gap: 1rem;"
            "  min-height: 4rem;"
            "  padding: 0.75rem clamp(1rem, 4vw, 3rem);"
            "  background: rgba(248, 250, 252, 0.94);"
            "  border-bottom: 1px solid var(--line);"
            "  backdrop-filter: blur(12px);"
            "}"
            ".brand { font-weight: 800; color: var(--ink); text-decoration: none; }"
            ".topnav { display: flex; gap: 0.5rem; align-items: center; flex-wrap: wrap; justify-content: flex-end; }"
            ".language-switch { display: inline-flex; gap: 0.25rem; align-items: center; }"
            ".language-switch a {"
            "  display: inline-flex;"
            "  align-items: center;"
            "  min-height: 2.25rem;"
            "  padding: 0.35rem 0.55rem;"
            "  border: 1px solid var(--line);"
            "  border-radius: 8px;"
            "  background: var(--panel);"
            "  color: var(--muted);"
            "  text-decoration: none;"
            "  font-size: 0.9rem;"
            "}"
            ".language-switch a.current { color: var(--panel); background: var(--teal); border-color: var(--teal); }"
            ".nav-pill {"
            "  display: inline-flex;"
            "  align-items: center;"
            "  min-height: 2.25rem;"
            "  padding: 0.35rem 0.7rem;"
            "  border: 1px solid var(--line);"
            "  border-radius: 8px;"
            "  background: var(--panel);"
            "  color: var(--ink);"
            "  text-decoration: none;"
            "  font-size: 0.95rem;"
            "}"
            ".hero {"
            "  display: grid;"
            "  grid-template-columns: minmax(0, 1fr) minmax(18rem, 34rem);"
            "  gap: clamp(1.25rem, 4vw, 4rem);"
            "  align-items: center;"
            "  padding: clamp(2rem, 7vw, 5rem) clamp(1rem, 4vw, 3rem) 2rem;"
            "  min-height: min(42rem, calc(100vh - 4rem));"
            "}"
            ".hero h1 {"
            "  max-width: 13ch;"
            "  margin: 0 0 1rem;"
            "  font-size: clamp(2.5rem, 6vw, 5.75rem);"
            "  line-height: 0.96;"
            "  letter-spacing: 0;"
            "}"
            ".hero p { max-width: 62ch; color: var(--muted); font-size: 1.08rem; }"
            ".hero-actions { display: flex; gap: 0.75rem; flex-wrap: wrap; margin-top: 1.5rem; }"
            ".button {"
            "  display: inline-flex;"
            "  align-items: center;"
            "  min-height: 2.75rem;"
            "  padding: 0.55rem 0.9rem;"
            "  border-radius: 8px;"
            "  border: 1px solid var(--ink);"
            "  color: var(--panel);"
            "  background: var(--ink);"
            "  text-decoration: none;"
            "  font-weight: 700;"
            "}"
            ".button.secondary { background: var(--panel); color: var(--ink); border-color: var(--line); }"
            ".pipeline-visual { margin: 0; }"
            ".pipeline-visual img {"
            "  display: block;"
            "  width: 100%;"
            "  aspect-ratio: 20 / 13;"
            "  object-fit: cover;"
            "  border: 1px solid var(--line);"
            "  border-radius: 8px;"
            "  background: #fff;"
            "}"
            ".pipeline-visual figcaption { margin-top: 0.7rem; color: var(--muted); font-size: 0.95rem; }"
            ".band { padding: 2.5rem clamp(1rem, 4vw, 3rem); border-top: 1px solid var(--line); }"
            ".band h2, .article h2 { margin: 0 0 1rem; font-size: clamp(1.45rem, 3vw, 2.1rem); letter-spacing: 0; }"
            ".course-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr)); gap: 0.85rem; }"
            ".lesson-card {"
            "  display: block;"
            "  min-height: 11rem;"
            "  padding: 1rem;"
            "  border: 1px solid var(--line);"
            "  border-radius: 8px;"
            "  background: var(--panel);"
            "  color: var(--ink);"
            "  text-decoration: none;"
            "}"
            ".lesson-card:hover { border-color: var(--teal); }"
            ".lesson-card strong { display: block; margin: 0.25rem 0 0.4rem; font-size: 1.05rem; }"
            ".lesson-number { color: var(--red); font-weight: 800; font-size: 0.86rem; }"
            ".lesson-card span:last-child { display: block; color: var(--muted); }"
            ".doc-shell {"
            "  display: grid;"
            "  grid-template-columns: 18rem minmax(0, 1fr);"
            "  gap: 2rem;"
            "  align-items: start;"
            "  padding: 2rem clamp(1rem, 4vw, 3rem);"
            "}"
            ".sidebar { position: sticky; top: 5.5rem; max-height: calc(100vh - 6rem); overflow: auto; }"
            ".sidebar a {"
            "  display: block;"
            "  padding: 0.45rem 0.55rem;"
            "  border-radius: 6px;"
            "  color: var(--muted);"
            "  text-decoration: none;"
            "}"
            ".sidebar a.current, .sidebar a:hover { background: #e7f6f3; color: var(--teal); }"
            ".article { max-width: 58rem; }"
            ".article-header { border-bottom: 1px solid var(--line); margin-bottom: 2rem; padding-bottom: 1.25rem; }"
            ".article-header h1 { margin: 0 0 0.75rem; font-size: clamp(2rem, 5vw, 4rem); line-height: 1; letter-spacing: 0; }"
            ".deck { color: var(--muted); font-size: 1.08rem; }"
            ".goals {"
            "  display: grid;"
            "  grid-template-columns: repeat(auto-fit, minmax(13rem, 1fr));"
            "  gap: 0.55rem;"
            "  padding: 0;"
            "  margin: 1.25rem 0 0;"
            "  list-style: none;"
            "}"
            ".goals li { border-left: 4px solid var(--amber); background: var(--panel); padding: 0.65rem 0.75rem; }"
            ".section { margin: 0 0 2.25rem; }"
            ".section p { color: var(--muted); }"
            ".code {"
            "  overflow: auto;"
            "  padding: 1rem;"
            "  border-radius: 8px;"
            "  border: 1px solid var(--code-edge);"
            "  background: var(--code);"
            "  color: #f9fafb;"
            "  line-height: 1.45;"
            "  font-size: 0.93rem;"
            "}"
            ".notes { margin: 0.75rem 0 0; padding-left: 1.2rem; color: var(--muted); }"
            ".pager { display: flex; justify-content: space-between; gap: 1rem; border-top: 1px solid var(--line); padding-top: 1.25rem; }"
            ".source-page .code { max-height: none; }"
            ".footer { padding: 2rem clamp(1rem, 4vw, 3rem); color: var(--muted); border-top: 1px solid var(--line); }"
            "@media (max-width: 820px) {"
            "  .hero, .doc-shell { grid-template-columns: 1fr; }"
            "  .hero { min-height: auto; }"
            "  .sidebar { position: static; max-height: none; border-bottom: 1px solid var(--line); padding-bottom: 1rem; }"
            "  .topbar { align-items: flex-start; flex-direction: column; }"
            "  .topnav { justify-content: flex-start; }"
            "}")))

(defun page-shell (title body &key (filename "index.html"))
  (format nil "<!doctype html>~%<html lang=\"~A\">~%~A~%~A~%</html>"
          (label :html-lang)
          (element
           "head" '()
           (void-element "meta" '("charset" "utf-8"))
           (void-element "meta" '("name" "viewport" "content" "width=device-width, initial-scale=1"))
           (element "title" '() (escape-html (format nil "~A - ~A" title (current-course-title))))
           (element "style" '() (css)))
          (element
           "body" '()
           (topbar filename)
           body
           (site-footer))))

(defun language-switcher (filename)
  (element
   "div" '("class" "language-switch" "aria-label" "Language")
   (with-output-to-string (stream)
     (dolist (language *available-languages*)
       (write-string
        (link-to (localized-page-url language filename)
                 (getf (cdr (assoc language *language-labels*)) :language-short)
                 :class (when (eq language *current-language*) "current"))
        stream)))))

(defun topbar (filename)
  (element
   "header" '("class" "topbar")
   (link-to "index.html" (current-course-title) :class "brand")
   (element "nav" '("class" "topnav" "aria-label" "Primary")
            (link-to "index.html#lessons" (label :lessons) :class "nav-pill")
            (link-to "compiler.html" (label :source) :class "nav-pill")
            (language-switcher filename))))

(defun site-footer ()
  (element
   "footer" '("class" "footer")
   (paragraph-html (label :footer))))

(defun index-page ()
  (page-shell
   (label :home-title)
   (concatenate
    'string
    (element
     "main" '()
     (element
      "section" '("class" "hero")
      (element
       "div" '()
       (element "h1" '() (escape-html (current-course-title)))
       (paragraph-html (current-course-deck))
       (element
        "div" '("class" "hero-actions")
        (link-to "#lessons" (label :start-course) :class "button")
        (link-to "compiler.html" (label :read-compiler) :class "button secondary")))
      (element
       "figure" '("class" "pipeline-visual")
       (void-element "img" (list "src" (asset-url "pipeline.png")
                                  "alt" (label :pipeline-alt)))
       (element "figcaption" '()
                (escape-html (label :pipeline-caption)))))
     (element
      "section" '("id" "lessons" "class" "band")
      (element "h2" '() (escape-html (label :lessons)))
      (lesson-grid))
     (element
      "section" '("class" "band")
      (element "h2" '() (escape-html (label :run-title)))
      (paragraph-html (label :run-copy))
      (code-block
       (format nil "(lbccl.site:build-site #p\"public/\")~%~%;; ~A"
               (label :test-note))))
     (element
      "section" '("class" "band")
      (element "h2" '() (escape-html (label :credits-title)))
      (paragraph-html (label :credits-copy))
      (link-to "https://compilers.iecc.com/crenshaw/"
               (label :credits-link)
               :class "button secondary"))))))

(defun lesson-grid ()
  (element
   "div" '("class" "course-grid")
   (with-output-to-string (stream)
     (dolist (lesson (current-lessons))
       (write-string
         (element
         "a" (list "class" "lesson-card" "href" (lesson-url lesson))
         (element "span" '("class" "lesson-number")
                  (escape-html (format nil "~A ~2,'0D"
                                       (label :lesson)
                                       (lesson-number lesson))))
         (element "strong" '() (escape-html (lesson-title lesson)))
         (element "span" '() (escape-html (lesson-deck lesson))))
        stream)))))

(defun sidebar (&optional current-lesson)
  (element
   "aside" '("class" "sidebar")
   (element
    "nav" '("aria-label" "Lessons")
    (with-output-to-string (stream)
      (dolist (lesson (current-lessons))
        (write-string
         (link-to (lesson-url lesson)
                  (format nil "~2,'0D. ~A" (lesson-number lesson) (lesson-title lesson))
                  :class (when (and current-lesson
                                    (string= (lesson-slug current-lesson)
                                             (lesson-slug lesson)))
                           "current"))
         stream))))))

(defun goals-html (lesson)
  (element
   "ul" '("class" "goals")
   (with-output-to-string (stream)
     (dolist (goal (lesson-goals lesson))
       (write-string (element "li" '() (escape-html goal)) stream)))))

(defun section-html (section)
  (element
   "section" '("class" "section")
   (element "h2" '() (escape-html (section-heading section)))
   (with-output-to-string (stream)
     (dolist (paragraph (section-paragraphs section))
       (write-string (paragraph-html paragraph) stream))
     (when (section-code section)
       (write-string (code-block (section-code section)) stream))
     (when (section-notes section)
       (write-string
        (element
         "ul" '("class" "notes")
         (with-output-to-string (notes-stream)
           (dolist (note (section-notes section))
             (write-string (element "li" '() (escape-html note)) notes-stream))))
        stream)))))

(defun previous-lesson (lesson)
  (let ((last nil))
    (dolist (candidate (current-lessons))
      (when (eq candidate lesson)
        (return last))
      (setf last candidate))))

(defun next-lesson (lesson)
  (loop for (current next) on (current-lessons)
        when (eq current lesson)
          return next))

(defun pager (lesson)
  (let ((previous (previous-lesson lesson))
        (next (next-lesson lesson)))
    (element
     "nav" '("class" "pager" "aria-label" "Lesson navigation")
     (if previous
         (link-to (lesson-url previous)
                  (format nil "~A: ~A" (label :previous) (lesson-title previous)))
         (element "span" '() ""))
     (if next
         (link-to (lesson-url next)
                  (format nil "~A: ~A" (label :next) (lesson-title next)))
         (link-to "compiler.html" (label :full-source))))))

(defun lesson-page (lesson)
  (page-shell
   (lesson-title lesson)
   (element
    "main" '("class" "doc-shell")
    (sidebar lesson)
    (element
     "article" '("class" "article")
     (element
      "header" '("class" "article-header")
      (element "span" '("class" "lesson-number")
               (escape-html (format nil "~A ~2,'0D"
                                    (label :lesson)
                                    (lesson-number lesson))))
      (element "h1" '() (escape-html (lesson-title lesson)))
      (element "p" '("class" "deck") (escape-html (lesson-deck lesson)))
      (goals-html lesson))
     (with-output-to-string (stream)
       (dolist (section (lesson-sections lesson))
         (write-string (section-html section) stream)))
     (pager lesson)))
   :filename (slug-file lesson)))

(defun read-file-as-string (pathname)
  (with-open-file (stream pathname :direction :input)
    (let ((string (make-string (file-length stream))))
      (read-sequence string stream)
      string)))

(defun source-page (root)
  (let ((source (read-file-as-string (merge-pathnames "src/tiny-compiler.lisp" root))))
    (page-shell
     (label :source-title)
     (element
      "main" '("class" "doc-shell source-page")
      (sidebar nil)
      (element
       "article" '("class" "article")
       (element
        "header" '("class" "article-header")
        (element "h1" '() (escape-html (label :source-title)))
        (element "p" '("class" "deck")
                 (escape-html (label :source-deck))))
       (code-block source)))
     :filename "compiler.html")))

(defun write-text-file (pathname content)
  (ensure-directories-exist pathname)
  (with-open-file (stream pathname
                          :direction :output
                          :if-exists :supersede
                          :if-does-not-exist :create)
    (write-string content stream)))

(defun write-u16-le (stream value)
  (write-byte (ldb (byte 8 0) value) stream)
  (write-byte (ldb (byte 8 8) value) stream))

(defun write-u32-le (stream value)
  (write-byte (ldb (byte 8 0) value) stream)
  (write-byte (ldb (byte 8 8) value) stream)
  (write-byte (ldb (byte 8 16) value) stream)
  (write-byte (ldb (byte 8 24) value) stream))

(defun make-canvas (width height red green blue)
  (let ((pixels (make-array (* width height 3)
                            :element-type '(unsigned-byte 8))))
    (loop for index below (* width height) do
      (let ((offset (* index 3)))
        (setf (aref pixels offset) red
              (aref pixels (+ offset 1)) green
              (aref pixels (+ offset 2)) blue)))
    pixels))

(defun pixel-offset (width x y)
  (* (+ x (* y width)) 3))

(defun set-pixel (pixels width height x y red green blue)
  (when (and (<= 0 x) (< x width) (<= 0 y) (< y height))
    (let ((offset (pixel-offset width x y)))
      (setf (aref pixels offset) red
            (aref pixels (+ offset 1)) green
            (aref pixels (+ offset 2)) blue))))

(defun fill-rect (pixels width height x y rect-width rect-height red green blue)
  (loop for row from y below (+ y rect-height) do
    (loop for col from x below (+ x rect-width) do
      (set-pixel pixels width height col row red green blue))))

(defun draw-line (pixels width height x1 y1 x2 y2 red green blue)
  (let* ((dx (abs (- x2 x1)))
         (dy (- (abs (- y2 y1))))
         (sx (if (< x1 x2) 1 -1))
         (sy (if (< y1 y2) 1 -1))
         (error (+ dx dy)))
    (loop
      (set-pixel pixels width height x1 y1 red green blue)
      (when (and (= x1 x2) (= y1 y2))
        (return))
      (let ((twice-error (* 2 error)))
        (when (>= twice-error dy)
          (incf error dy)
          (incf x1 sx))
        (when (<= twice-error dx)
          (incf error dx)
          (incf y1 sy))))))

(defun fill-triangle-right (pixels width height x y size red green blue)
  (loop for row from (- y size) to (+ y size)
        for span = (- size (abs (- row y))) do
          (loop for col from x to (+ x span) do
            (set-pixel pixels width height col row red green blue))))

(defun draw-pipeline-asset (pathname)
  (let* ((width 1200)
         (height 780)
         (pixels (make-canvas width height 248 250 252))
         (blocks '((80 170 170 180 15 118 110)
                   (300 300 170 180 185 28 28)
                   (520 170 170 180 183 121 31)
                   (740 300 170 180 24 24 27)
                   (960 170 170 180 15 118 110))))
    (loop for y from 0 below height by 24 do
      (draw-line pixels width height 0 y width (+ y 120) 232 235 239))
    (dolist (block blocks)
      (destructuring-bind (x y w h r g b) block
        (fill-rect pixels width height x y w h r g b)
        (fill-rect pixels width height (+ x 12) (+ y 12) (- w 24) 12 255 255 255)
        (fill-rect pixels width height (+ x 12) (+ y 42) (- w 55) 10 255 255 255)
        (fill-rect pixels width height (+ x 12) (+ y 70) (- w 75) 10 255 255 255)))
    (loop for (x1 y1 x2 y2) in '((250 260 300 380)
                                 (470 390 520 260)
                                 (690 260 740 390)
                                 (910 390 960 260)) do
      (loop for offset from -3 to 3 do
        (draw-line pixels width height x1 (+ y1 offset) x2 (+ y2 offset) 39 39 42))
      (fill-triangle-right pixels width height x2 y2 22 39 39 42))
    (write-png pathname pixels width height)))

(defun ascii-bytes (string)
  (let ((bytes (make-array (length string) :element-type '(unsigned-byte 8))))
    (loop for index below (length string) do
      (setf (aref bytes index) (char-code (char string index))))
    bytes))

(defun write-u32-be (stream value)
  (write-byte (ldb (byte 8 24) value) stream)
  (write-byte (ldb (byte 8 16) value) stream)
  (write-byte (ldb (byte 8 8) value) stream)
  (write-byte (ldb (byte 8 0) value) stream))

(defun write-byte-vector (stream vector)
  (loop for byte across vector do
    (write-byte byte stream)))

(defun make-byte-buffer ()
  (make-array 0
              :element-type '(unsigned-byte 8)
              :adjustable t
              :fill-pointer 0))

(defun buffer-byte (buffer byte)
  (vector-push-extend byte buffer))

(defun buffer-u16-le (buffer value)
  (buffer-byte buffer (ldb (byte 8 0) value))
  (buffer-byte buffer (ldb (byte 8 8) value)))

(defun buffer-u32-be (buffer value)
  (buffer-byte buffer (ldb (byte 8 24) value))
  (buffer-byte buffer (ldb (byte 8 16) value))
  (buffer-byte buffer (ldb (byte 8 8) value))
  (buffer-byte buffer (ldb (byte 8 0) value)))

(defun buffer-vector (buffer vector &key (start 0) end)
  (loop for index from start below (or end (length vector)) do
    (buffer-byte buffer (aref vector index))))

(defun adler32 (data)
  (let ((a 1)
        (b 0))
    (loop for byte across data do
      (setf a (mod (+ a byte) 65521)
            b (mod (+ b a) 65521)))
    (logior (ash b 16) a)))

(defun crc32-for (type data)
  (let ((crc #xffffffff))
    (labels ((step-byte (byte)
               (setf crc (logxor crc byte))
               (loop repeat 8 do
                 (setf crc
                       (if (oddp crc)
                           (logxor (ash crc -1) #xedb88320)
                           (ash crc -1)))
                 (setf crc (logand crc #xffffffff)))))
      (loop for byte across type do (step-byte byte))
      (loop for byte across data do (step-byte byte)))
    (logxor crc #xffffffff)))

(defun png-raw-data (pixels width height)
  (let ((raw (make-array (* height (1+ (* width 3)))
                         :element-type '(unsigned-byte 8)))
        (raw-offset 0))
    (loop for y below height do
      (setf (aref raw raw-offset) 0)
      (incf raw-offset)
      (loop for x below width do
        (let ((pixel (pixel-offset width x y)))
          (setf (aref raw raw-offset) (aref pixels pixel)
                (aref raw (+ raw-offset 1)) (aref pixels (+ pixel 1))
                (aref raw (+ raw-offset 2)) (aref pixels (+ pixel 2)))
          (incf raw-offset 3))))
    raw))

(defun zlib-store (data)
  (let ((buffer (make-byte-buffer))
        (offset 0)
        (length (length data)))
    (buffer-byte buffer #x78)
    (buffer-byte buffer #x01)
    (loop while (< offset length) do
      (let* ((remaining (- length offset))
             (chunk-size (min remaining 65535))
             (finalp (= (+ offset chunk-size) length)))
        (buffer-byte buffer (if finalp 1 0))
        (buffer-u16-le buffer chunk-size)
        (buffer-u16-le buffer (logxor chunk-size #xffff))
        (buffer-vector buffer data :start offset :end (+ offset chunk-size))
        (incf offset chunk-size)))
    (buffer-u32-be buffer (adler32 data))
    buffer))

(defun png-chunk (stream type-string data)
  (let ((type (ascii-bytes type-string)))
    (write-u32-be stream (length data))
    (write-byte-vector stream type)
    (write-byte-vector stream data)
    (write-u32-be stream (crc32-for type data))))

(defun write-png (pathname pixels width height)
  (ensure-directories-exist pathname)
  (let ((signature #(137 80 78 71 13 10 26 10))
        (ihdr (make-byte-buffer)))
    (buffer-u32-be ihdr width)
    (buffer-u32-be ihdr height)
    (buffer-byte ihdr 8)
    (buffer-byte ihdr 2)
    (buffer-byte ihdr 0)
    (buffer-byte ihdr 0)
    (buffer-byte ihdr 0)
    (with-open-file (stream pathname
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create
                            :element-type '(unsigned-byte 8))
      (write-byte-vector stream signature)
      (png-chunk stream "IHDR" ihdr)
      (png-chunk stream "IDAT" (zlib-store (png-raw-data pixels width height)))
      (png-chunk stream "IEND" (make-array 0 :element-type '(unsigned-byte 8))))))

(defun write-bmp (pathname pixels width height)
  (ensure-directories-exist pathname)
  (let* ((row-bytes (* width 3))
         (padding (mod (- 4 (mod row-bytes 4)) 4))
         (padded-row-bytes (+ row-bytes padding))
         (pixel-data-size (* padded-row-bytes height))
         (file-size (+ 54 pixel-data-size)))
    (with-open-file (stream pathname
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create
                            :element-type '(unsigned-byte 8))
      (write-byte #x42 stream)
      (write-byte #x4d stream)
      (write-u32-le stream file-size)
      (write-u16-le stream 0)
      (write-u16-le stream 0)
      (write-u32-le stream 54)
      (write-u32-le stream 40)
      (write-u32-le stream width)
      (write-u32-le stream height)
      (write-u16-le stream 1)
      (write-u16-le stream 24)
      (write-u32-le stream 0)
      (write-u32-le stream pixel-data-size)
      (write-u32-le stream 2835)
      (write-u32-le stream 2835)
      (write-u32-le stream 0)
      (write-u32-le stream 0)
      (loop for y downfrom (1- height) to 0 do
        (loop for x below width do
          (let ((offset (pixel-offset width x y)))
            (write-byte (aref pixels (+ offset 2)) stream)
            (write-byte (aref pixels (+ offset 1)) stream)
            (write-byte (aref pixels offset) stream)))
        (loop repeat padding do (write-byte 0 stream))))))

(defun language-output-directory (output language)
  (ensure-directory
   (ecase language
     (:en output)
     (:pt-br (merge-pathnames "pt-br/" output)))))

(defun build-language-pages (language output root)
  (let ((*current-language* language)
        (language-output (language-output-directory output language)))
    (write-text-file (path language-output "index.html") (index-page))
    (dolist (lesson (current-lessons))
      (write-text-file (path language-output (slug-file lesson))
                       (lesson-page lesson)))
    (write-text-file (path language-output "compiler.html")
                     (source-page root))))

(defun build-site (&optional (output-directory #p"public/"))
  (let* ((root (make-pathname :name nil :type nil
                              :defaults (or *load-truename* *default-pathname-defaults*)))
         (output (ensure-directory output-directory))
         (assets (ensure-directory (merge-pathnames "assets/" output))))
    (dolist (language *available-languages*)
      (build-language-pages language output root))
    (draw-pipeline-asset (path assets "pipeline.png"))
    output))
